/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package voting_app;

import java.awt.Color;

/**
 *
 * @author Gouhar Ali
 */
public class ADMIN_MAIN extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN_MAIN
     */
    public ADMIN_MAIN() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanal1 = new panal.bgpanal();
        pane21 = new panal.pane2();
        jLabel2 = new javax.swing.JLabel();
        pane31 = new panal.pane3();
        jLabel3 = new javax.swing.JLabel();
        pane32 = new panal.pane3();
        pane34 = new panal.pane3();
        jLabel6 = new javax.swing.JLabel();
        pane33 = new panal.pane3();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pane35 = new panal.pane3();
        pane36 = new panal.pane3();
        jLabel5 = new javax.swing.JLabel();
        pane37 = new panal.pane3();
        pane38 = new panal.pane3();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgpanal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        pane21.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 20, 40));

        bgpanal1.add(pane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 794, 40));

        pane31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pane31MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icons8-candidates-100.png"))); // NOI18N
        jLabel3.setText("Create Candidate");
        pane31.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 580, 100));

        bgpanal1.add(pane31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 640, 100));

        pane32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pane32MouseClicked(evt);
            }
        });
        pane32.add(pane34, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, 100));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Logout");
        pane32.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        bgpanal1.add(pane32, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 630, 130, 60));

        pane33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pane33MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icons8-voters-100.png"))); // NOI18N
        jLabel4.setText("View Voters");
        pane33.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 560, 100));

        bgpanal1.add(pane33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 640, 100));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN MAIN");
        jLabel1.setOpaque(true);
        bgpanal1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 750, -1));

        pane35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pane35MouseClicked(evt);
            }
        });
        pane35.add(pane36, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, 100));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icons8-result-100.png"))); // NOI18N
        jLabel5.setText("View Result");
        pane35.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 560, -1));

        bgpanal1.add(pane35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 640, 100));

        pane37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pane37MouseClicked(evt);
            }
        });
        pane37.add(pane38, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, 100));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icons8-elections-100.png"))); // NOI18N
        jLabel7.setText("Elections");
        pane37.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 550, 80));

        bgpanal1.add(pane37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 640, 100));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("SOFTWARE BY Muhammad Uzair              PH no : 03335323758");
        bgpanal1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 590, 30));

        getContentPane().add(bgpanal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void pane32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pane32MouseClicked
        // TODO add your handling code here:
        dispose();
        new ADMIN_LOGIN().setVisible(true);
        
    }//GEN-LAST:event_pane32MouseClicked

    private void pane37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pane37MouseClicked
        // TODO add your handling code here:
        dispose();
        new ELections().setVisible(true);
    }//GEN-LAST:event_pane37MouseClicked

    private void pane31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pane31MouseClicked
        // TODO add your handling code here:

        dispose();
        new CANDIDATE().setVisible(true);

    }//GEN-LAST:event_pane31MouseClicked

    private void pane33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pane33MouseClicked
        // TODO add your handling code here:
        dispose();
        new VIEW_VOTERS().setVisible(true);
    }//GEN-LAST:event_pane33MouseClicked

    private void pane35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pane35MouseClicked
        // TODO add your handling code here:
        dispose();
        new Results().setVisible(true);
    }//GEN-LAST:event_pane35MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN_MAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panal.bgpanal bgpanal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private panal.pane2 pane21;
    private panal.pane3 pane31;
    private panal.pane3 pane32;
    private panal.pane3 pane33;
    private panal.pane3 pane34;
    private panal.pane3 pane35;
    private panal.pane3 pane36;
    private panal.pane3 pane37;
    private panal.pane3 pane38;
    // End of variables declaration//GEN-END:variables
}
