/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package voting_app;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User1
 */
public class LODING extends javax.swing.JFrame {

    /**
     * Creates new form loding
     */
     
   
    public LODING() {
        initComponents();
        setBackground(new Color(0,0,0,0));
       
    }

    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane31 = new panal.pane3();
        lodingbar = new javax.swing.JProgressBar();
        lodevalue = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lodingbar.setBackground(new java.awt.Color(255, 255, 255));
        lodingbar.setFont(new java.awt.Font("Agency FB", 0, 10)); // NOI18N
        lodingbar.setForeground(new java.awt.Color(255, 153, 153));
        lodingbar.setBorder(null);
        lodingbar.setFocusable(false);
        pane31.add(lodingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 740, 20));

        lodevalue.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lodevalue.setForeground(new java.awt.Color(204, 0, 0));
        pane31.add(lodevalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 50, 30));

        msg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        msg.setForeground(new java.awt.Color(0, 0, 255));
        pane31.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 410, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("PLEASE WAIT");
        pane31.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        pane31.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/voting-box.png"))); // NOI18N
        pane31.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 520, 540));

        getContentPane().add(pane31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        
        jLabel2.setBackground(Color.red);
        
        
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel2.setBackground(Color.WHITE);
        
        
    }//GEN-LAST:event_jLabel2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LODING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LODING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LODING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LODING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
               
               LODING s=new LODING();
               s.setVisible(true);
              try{
                   for(int i=0;i<=100;i++){
                       Thread.sleep(60);
                       s.lodevalue.setText(i+"%");
                       if (i<10){
                           s.msg.setText("LODING");
                       }
                       if (i==10){
                           s.msg.setText("CONNECTING DATABASE REQUISTING OPEN XAMPP");
                          try{
                               Process process = Runtime.getRuntime().exec("C:\\xampp\\mysql\\bin\\mysqld.exe");
                          }catch(Exception e)
                          {
                               JOptionPane.showMessageDialog(s,"DATABASE NOT FOUND\n"+e);
                               System.exit(0);
                          }
                       }
                       if (i==40){
                           s.msg.setText("DATABASE CONNECTED");
                       }
                       if (i>70){
                           s.msg.setText("PLEASE WAIT. LOADING");
                           
                       }
                       if(i==100){
                           s.dispose();
                           new MAIN().setVisible(true);
                       }
                       s.lodingbar.setValue(i);
                       
                   }
               }catch(Exception e){
                   JOptionPane.showMessageDialog(s, e);
               }
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lodevalue;
    private javax.swing.JProgressBar lodingbar;
    private javax.swing.JLabel msg;
    private panal.pane3 pane31;
    // End of variables declaration//GEN-END:variables
}
