/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package voting_app;

import code_files.ConnectDB;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gouhar Ali
 */
public class SELECT_ELECTION extends javax.swing.JFrame {

    /**
     * Creates new form SELECT_ELECTION
    */
    
    Connection con ;
    PreparedStatement str;
    ResultSet rs;
    public SELECT_ELECTION() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        ConnectDB c = new ConnectDB();
        con = c.Connect();
        getcategory();
    }

         
    public void getcategory(){
        
        try{
            str=con.prepareStatement("select* from `elections`");
            rs=str.executeQuery();
            while(rs.next()){
                IDtxt.addItem(rs.getString("ID"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    
    
     public void Clear(){
          NAMEtxt.setText("");
          DATEtxt.setText("");    
          totalCandidate.setText("");
      }
    
    
     public void getALLDATA()
    {
        int c;
        try {
            
            String id = IDtxt.getSelectedItem().toString();
            
          
            str=con.prepareStatement ("SELECT* from elections where ID='"+id+"'");
            rs=str.executeQuery();
           
            
            if (rs.next()){
               NAMEtxt.setText(rs.getString("NAME"));
               DATEtxt.setText(rs.getString("DATE"));
               totalCandidate.setText(""+getNoOfCandidates()) ;
            }
            else{
                Clear();
            }
            
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(this,ex,"CONNECTION ",3);
        }
    }
    
    
    
    
    public int getNoOfCandidates()
    {
        int c;
        try {
           
          
            str=con.prepareStatement ("SELECT COUNT(*) from candidate_detail where EID='"+IDtxt.getSelectedItem()+"'");
            rs=str.executeQuery();
            if (rs.next()) {                
                c=rs.getInt("count(*)");
                System.out.println();
                return c;
            }
            
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(this,ex,"CONNECTION ",3);
        }
        return 0;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanal1 = new panal.bgpanal();
        pane21 = new panal.pane2();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pane31 = new panal.pane3();
        IDtxt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        DATEtxt = new javax.swing.JTextField();
        NAMEtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pane22 = new panal.pane2();
        jLabel9 = new javax.swing.JLabel();
        totalCandidate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pane23 = new panal.pane2();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgpanal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pane21.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 20, 30));

        bgpanal1.add(pane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 649, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Initiate Elections                                انتخابات شروع کریں ");
        jLabel2.setOpaque(true);
        bgpanal1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 570, 50));

        IDtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IDtxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        IDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtxtActionPerformed(evt);
            }
        });
        pane31.add(IDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 190, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATE");
        pane31.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));

        DATEtxt.setEditable(false);
        DATEtxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DATEtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DATEtxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        DATEtxt.setFocusable(false);
        DATEtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DATEtxtActionPerformed(evt);
            }
        });
        pane31.add(DATEtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, 30));

        NAMEtxt.setEditable(false);
        NAMEtxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NAMEtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NAMEtxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        NAMEtxt.setFocusable(false);
        NAMEtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEtxtActionPerformed(evt);
            }
        });
        pane31.add(NAMEtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 250, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ELECTION ID");
        pane31.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ELECTION ");
        pane31.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("تاریخ");
        pane31.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 90, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("انتخابات کی ایڈی نمبر ");
        pane31.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 20, 140, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("انتخابات ");
        pane31.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 90, 30));

        pane22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pane22MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Start Elections          انتخابات شروع کریں");
        pane22.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 320, 40));

        pane31.add(pane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 400, 60));

        totalCandidate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalCandidate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalCandidate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Total Candidates___کل امیدوار", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        pane31.add(totalCandidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 250, 50));

        bgpanal1.add(pane31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 490, 300));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Please select Election to Start Voting           ووٹنگ شروع کرنے کے لیے براے کرم الیکشن کا انتخاب کریں۔");
        bgpanal1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 630, 30));

        pane23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pane23MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("BACK");
        pane23.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        bgpanal1.add(pane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 130, 40));

        jLabel12.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SOFTWARE BY Muhammad Uzair      PH no : 03335323758");
        bgpanal1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 420, 40));

        getContentPane().add(bgpanal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void DATEtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DATEtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DATEtxtActionPerformed

    private void NAMEtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEtxtActionPerformed

    private void IDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtxtActionPerformed
        // TODO add your handling code here:
        getALLDATA();
    }//GEN-LAST:event_IDtxtActionPerformed

    private void pane23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pane23MouseClicked
        // TODO add your handling code here:
        dispose();
        new VOTER_MAIN().setVisible(true);
    }//GEN-LAST:event_pane23MouseClicked

    private void pane22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pane22MouseClicked
        // TODO add your handling code here:
        if(IDtxt.getSelectedItem().toString().equals("Select") || NAMEtxt.getText().equals("") || DATEtxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Election Must Be Selected","Invalid Selection",2);
            return;
        }
        
        int noOfCan=Integer.parseInt(totalCandidate.getText());
        if(noOfCan<=1){
            JOptionPane.showMessageDialog(this, "No oF Candidates Must be 2 or More","Invalid Candidates",2);
            return;
        }
        
        dispose();
        new START_VOTING(IDtxt.getSelectedItem().toString(),NAMEtxt.getText()).setVisible(true);
        
    }//GEN-LAST:event_pane22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SELECT_ELECTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SELECT_ELECTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SELECT_ELECTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SELECT_ELECTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SELECT_ELECTION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DATEtxt;
    private javax.swing.JComboBox<String> IDtxt;
    private javax.swing.JTextField NAMEtxt;
    private panal.bgpanal bgpanal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private panal.pane2 pane21;
    private panal.pane2 pane22;
    private panal.pane2 pane23;
    private panal.pane3 pane31;
    private javax.swing.JLabel totalCandidate;
    // End of variables declaration//GEN-END:variables
}
