/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package voting_app;

import java.awt.Color;

/**
 *
 * @author Gouhar Ali
 */
public class VOTER_MAIN extends javax.swing.JFrame {

    /**
     * Creates new form VOTER_MAIN
     */
    public VOTER_MAIN() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanal1 = new panal.bgpanal();
        pane21 = new panal.pane2();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pane31 = new panal.pane3();
        jLabel3 = new javax.swing.JLabel();
        pane32 = new panal.pane3();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pane33 = new panal.pane3();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgpanal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pane21.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 20, 20));

        bgpanal1.add(pane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VOTER MAIN");
        jLabel2.setOpaque(true);
        bgpanal1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 850, -1));

        pane31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pane31MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BACK");
        pane31.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 180, 30));

        bgpanal1.add(pane31, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 240, 50));

        pane32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pane32MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icons8-candidates-100.png"))); // NOI18N
        jLabel4.setText("VIEW CANDIDATES                امیدواروں کو دیکھیں");
        pane32.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 560, 110));

        bgpanal1.add(pane32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 560, 130));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SOFTWARE BY Muhammad Uzair           PH no : 03335323758");
        bgpanal1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 450, 30));

        pane33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pane33MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icons8-voting-100.png"))); // NOI18N
        jLabel5.setText("START VOTING                              ووٹ شروع کرے");
        pane33.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 560, 110));

        bgpanal1.add(pane33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 560, 130));

        getContentPane().add(bgpanal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void pane31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pane31MouseClicked
        // TODO add your handling code here:

        dispose();
        new  MAIN().setVisible(true);

    }//GEN-LAST:event_pane31MouseClicked

    private void pane32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pane32MouseClicked
        // TODO add your handling code here:
        dispose();
       new VIEW_CANDIDATES().setVisible(true);
    }//GEN-LAST:event_pane32MouseClicked

    private void pane33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pane33MouseClicked
        // TODO add your handling code here:
        dispose();
        new SELECT_ELECTION().setVisible(true);
    }//GEN-LAST:event_pane33MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VOTER_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VOTER_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VOTER_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VOTER_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VOTER_MAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panal.bgpanal bgpanal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private panal.pane2 pane21;
    private panal.pane3 pane31;
    private panal.pane3 pane32;
    private panal.pane3 pane33;
    // End of variables declaration//GEN-END:variables
}
